name: test

on:
  push:
    branches:
      - 'master'
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'master'
      - 'v*'
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.0
      -
        name: Prepare
        id: prepare
        run: |
          echo ::set-output name=build_tag::test
          echo ::set-output name=container_name::ftpgrab
          echo ::set-output name=running_timeout::120
          echo ::set-output name=running_log_check::Finished
      -
        name: Docker Build
        run: |
          docker build --tag ${{ steps.prepare.outputs.build_tag }} --file Dockerfile .
      -
        name: Create network
        run: |
          docker network create -d bridge ${{ steps.prepare.outputs.container_name }}
      -
        name: Start Pure-FTPd container
        run: |
          echo "foo:\$2a\$08\$H2v8vXFqPddF1jHU1tN2vurj./NBDmReoNEl7iY.WgEGzF/NCTBjK:$(id -u):$(id -g)::/home/foo/./::::::::::::" > /tmp/pureftpd.passwd
          echo "-d -d" > /tmp/pureftpd.flags
          cat /tmp/pureftpd.passwd

          docker run -d --name pureftpd --hostname pureftpd \
            --network ${{ steps.prepare.outputs.container_name }} \
            -e "AUTH_METHOD=puredb" \
            -e "SECURE_MODE=false" \
            -v "${HOME}/warmup:/home/foo" \
            -v "/tmp/pureftpd.passwd:/data/pureftpd.passwd" \
            -v "/tmp/pureftpd.flags:/data/pureftpd.flags" \
            crazymax/pure-ftpd:1.0.47

          sleep 5
          docker exec -i pureftpd pure-pw show foo
      -
        name: Start container
        run: |
          docker run -d --name ${{ steps.prepare.outputs.container_name }} \
            --link pureftpd \
            --network ${{ steps.prepare.outputs.container_name }} \
            -e "SCHEDULE=*/30 * * * *" \
            -e "LOG_LEVEL=debug" \
            -e "LOG_NOCOLOR=true" \
            -v "$(pwd)/.res/ftpgrab.test.yml:/ftpgrab.yml:ro" \
            ${{ steps.prepare.outputs.build_tag }}
      -
        name: Test run
        run: |
          TIMEOUT=$((SECONDS + ${{ steps.prepare.outputs.running_timeout }}))
          while read LOGLINE; do
            echo ${LOGLINE}
            if [[ ${LOGLINE} == *"${{ steps.prepare.outputs.running_log_check }}"* ]]; then
              echo "🎉 Container up!"
              break
            fi
            if [[ $SECONDS -gt ${TIMEOUT} ]]; then
              >&2 echo "❌ Failed to run ${{ steps.prepare.outputs.container_name }} container"
              exit 1
            fi
          done < <(docker logs -f ${{ steps.prepare.outputs.container_name }} 2>&1)

          CONTAINER_STATUS=$(docker container inspect --format "{{.State.Status}}" ${{ steps.prepare.outputs.container_name }})
          if [[ ${CONTAINER_STATUS} != "running" ]]; then
            >&2 echo "❌ Container ${{ steps.prepare.outputs.container_name }} returned status '$CONTAINER_STATUS'"
            exit 1
          fi
      -
        name: Pure-FTPd logs
        if: always()
        run: |
          docker logs pureftpd
          docker rm -f pureftpd > /dev/null 2>&1 || true
      -
        name: Container logs
        if: always()
        run: |
          docker logs ${{ steps.prepare.outputs.container_name }}
          docker rm -f ${{ steps.prepare.outputs.container_name }} > /dev/null 2>&1 || true
